-- Setting files
require "settings.options"
require "settings.keymaps"

require "plugins"
require "plugins.alpha"
require "plugins.autopairs"
require "plugins.cmp"
require "plugins.colorscheme"
require "plugins.nvim-tree"
require "plugins.project"
require "plugins.telescope"
require "plugins.lsp"
require "plugins.bookmarks"
require "plugins.lualine"
require "plugins.toggleterm"
require "plugins.bufferline"
